name: Deploy Sentinel Analytic Rules

on:
  push:
    paths:
      - 'sentinel-analytic-rules/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Analytic Rules
      run: |
        for rule in sentinel-analytic-rules/*.json; do
          az sentinel alert-rule create \
            --resource-group fy25 \
            --workspace-name EastUSa \
            --rule-id $(basename $rule .json) \
            --location East US \
            --content @$rule
        done
