- name: Deploy Analytic Rules
  run: |
    for rule in sentinel-analytic-rules/*.json; do
      az sentinel alert-rule create \
        --resource-group fy25 \
        --workspace-name EastUSa \
        --name $(basename $rule .json) \
        --properties @$rule
    done
